[package]
name = "burn-test"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version="0.14.0", features = ["candle"] }
burn-import = { version="0.14.0" }
lazy_static = "1.5.0"
ndarray = "0.16.1"
ndarray-npy = "0.9.1"

